name: API Pipeline

on:
  push:
    branches: ["master"]

jobs:
  tests:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Ubuntu
        run: sh .github/scripts/update-os.sh

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install PNPM
        run: sh .github/scripts/install-pnpm.sh

      - name: Install Dependencies
        run: pnpm i

      - name: Runing Tests
        run: pnpm test:cov

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: coverage/
  build:
    runs-on: ubuntu-latest
    needs:
      - tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Ubuntu
        run: sh .github/scripts/update-os.sh

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install PNPM
        run: sh .github/scripts/install-pnpm.sh

      - name: Install Dependencies
        run: pnpm i

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: builds
          path: dist/
  notification:
    runs-on: ubuntu-latest
    env:
      EMAIL_TO_SEND: ${{ secrets.EMAIL_TO_SEND }}
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
    needs:
      - build
    steps:
      name: Update Ubuntu
      run: sh .github/scripts/update-os.sh

        - name: Download artifacts
          uses: actions/download-artifact@v4
          with:
            name: reports

        - name: Update Ubuntu
          run: sh .github/scripts/send-email.sh